### ISSUE TITLE
Fenstergrösse

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#1]
(Priorität hoch)

Fenstergrösse an Bildschirm anpassen! (Buttons zum Speichern/Specimen wechseln teils ausserhalb vom Bildschirm)

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

**Comment by GenieTim** [comment]
Might be fixed in [v1.9.2](https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/v1.9.2-SNAPSHOT) for the edit specimen window – at least it includes scroll bars on too small screens. Additionally, it saves the window size and location, although sometimes with a certain delay.
