### ISSUE TITLE
Data search: Entry by

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#12]
Priority medium: 

Suche nach Entry By funktioniert nicht

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

**Comment by GenieTim** [comment]
Should be fixed in [V1.10.0](https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/v1.10.0-SNAPSHOT)
