### ISSUE TITLE
Search function works only when results available

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#13]
Priority medium:

Suche funktioniert nicht wenn keine Resultate vorhanden sind (Bsp. «%gnl%» in Verbatim Locality)

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

**Comment by GenieTim** [comment]
Should be fixed in [v1.9.2](https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/v1.9.2-SNAPSHOT).
