### ISSUE TITLE
2 Bilder pro Specimen

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#2]
(Priorität hoch)

Rückseite der Zettel lässt sich nicht anzeigen! Das heisst, es wird nur ein Bild pro Specimen angezeigt, auch wenn zwei vorhanden sind. Man kann nicht zum zweiten Bild wechseln.

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

**Comment by GenieTim** [comment]
Should be fixed in [v1.9.2](https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/v1.9.2-SNAPSHOT).
