### ISSUE TITLE
History

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#4]
(Priorität mittel)

History funktioniert nicht (Wird nicht angezeigt, Programm stürzt ab, siehe imagecapture191018-1040.log)

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

[imagecapture191018-1040.log](https://github.com/ETHEntColl/DataShot_DesktopApp_ETH/files/3743763/imagecapture191018-1040.log)

**Comment by GenieTim** [comment]
Thanks for the log. Should be fixed in [v1.9.2](https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/v1.9.2-SNAPSHOT).
