### ISSUE TITLE
Speichern nach Copy Previous

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#5]
Nach Copy Prev speichern manchmal nicht möglich 

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

[imagecapture191017-1248.log](https://github.com/ETHEntColl/DataShot_DesktopApp_ETH/files/3743766/imagecapture191017-1248.log)

**Comment by GenieTim** [comment]
Moved conversation to https://github.com/BernhardWebstudio/DataShot_DesktopApp/issues/17
