### ISSUE TITLE
Status georeference button

### ISSUE THREAD

**Issue by greeffm** [ETHEntColl/DataShot_DesktopApp_ETH#9]
Priority medium:

Georefernece wird als (1) angezeigt bevor etwas ausgefüllt ist

Fragen bitte direkt an: ruben.zwicker@usys.ethz.ch

**Comment by GenieTim** [comment]
See also https://github.com/BernhardWebstudio/DataShot_DesktopApp/issues/20; should be fixed in [v1.10.0](https://github.com/BernhardWebstudio/DataShot_DesktopApp/issues/20)
